#!/usr/bin/env bash
# Configures an Ubuntu server:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.backup

tmp_file=$(mktemp)

echo "127.0.0.2	localhost" > "$tmp_file"
echo "8.8.8.8	facebook.com" >> "$tmp_file"

cat ~/hosts.backup >> "$tmp_file"

sudo mv "$tmp_file" /etc/hosts

rm ~/hosts.backup

